<?php
/**
 * Model for app_themes
 * 
 * Generated by BlackPHP
 */

class app_themes_model
{
	use ORM;

	/** @var int $theme_id ID de la tabla */
	private $theme_id;

	/** @var string $theme_name Nombre del tema */
	private $theme_name;

	/** @var string $theme_url Nombre de la carpeta pública */
	private $theme_url;


	/** @var string $_table_name Nombre de la tabla */
	private static $_table_name = "app_themes";

	/** @var string $_primary_key Llave primaria */
	private static $_primary_key = "theme_id";

	/** @var bool $_timestamps La tabla usa marcas de tiempo para la inserción y edición de datos */
	private static $_timestamps = false;

	/** @var bool $_soft_delete La tabla soporta borrado suave */
	private static $_soft_delete = false;

	/**
	 * Constructor de la clase
	 * 
	 * Se inicializan las propiedades con los valores de los campos default
	 * de la base de datos
	 **/
	public function __construct()
	{
	}

	public function getTheme_id()
	{
		return $this->theme_id;
	}

	public function setTheme_id($value)
	{
		$this->theme_id = $value === null ? null : (int)$value;
	}

	public function getTheme_name()
	{
		return $this->theme_name;
	}

	public function setTheme_name($value)
	{
		$this->theme_name = $value === null ? null : (string)$value;
	}

	public function getTheme_url()
	{
		return $this->theme_url;
	}

	public function setTheme_url($value)
	{
		$this->theme_url = $value === null ? null : (string)$value;
	}

	public function users()
	{
		users::flush();
		return users::where("theme_id", $this->theme_id);
	}
}
?>
