<?php
/**
 * Model for app_modules
 * 
 * Generated by BlackPHP
 */

class app_modules_model extends Model
{
	/** @var int $module_id ID de la tabla */
	private $module_id;

	/** @var string $module_name Nombre del módulo */
	private $module_name;

	/** @var string $module_url URL del módulo */
	private $module_url;

	/** @var string $module_key Tecla de acceso rápido */
	private $module_key;

	/** @var string $module_description Descripción del módulo */
	private $module_description;

	/** @var int $default_order Orden por defecto */
	private $default_order;

	/** @var int $status Estado 0:inactivo, 1:activo */
	private $status;

	/**
	 * Constructor de la clase
	 * 
	 * Inicializa las propiedades table_name y primary_key
	 */
	public function __construct()
	{
		$this->table_name = "app_modules";
		$this->primary_key = "module_id";
	}

	public function getModule_id()
	{
		return $this->module_id;
	}

	public function setModule_id($value)
	{
		$this->module_id = $value;
	}

	public function getModule_name()
	{
		return $this->module_name;
	}

	public function setModule_name($value)
	{
		$this->module_name = $value;
	}

	public function getModule_url()
	{
		return $this->module_url;
	}

	public function setModule_url($value)
	{
		$this->module_url = $value;
	}

	public function getModule_key()
	{
		return $this->module_key;
	}

	public function setModule_key($value)
	{
		$this->module_key = $value;
	}

	public function getModule_description()
	{
		return $this->module_description;
	}

	public function setModule_description($value)
	{
		$this->module_description = $value;
	}

	public function getDefault_order()
	{
		return $this->default_order;
	}

	public function setDefault_order($value)
	{
		$this->default_order = $value;
	}

	public function getStatus()
	{
		return $this->status;
	}

	public function setStatus($value)
	{
		$this->status = $value;
	}
}
?>
