<?php
/**
 * Model for app_actions
 * 
 * Generated by BlackPHP
 */

class app_actions_model extends Model
{
	/** @var int $action_id ID del registro */
	private $action_id;

	/** @var string $action_key Clave de la acción */
	private $action_key;

	/** @var string $infinitive_verb Verbo en infinitivo */
	private $infinitive_verb;

	/** @var string $past_verb Verbo en pasado */
	private $past_verb;

	/**
	 * Constructor de la clase
	 * 
	 * Inicializa las propiedades table_name y primary_key
	 */
	public function __construct()
	{
		$this->table_name = "app_actions";
		$this->primary_key = "action_id";
	}

	public function getAction_id()
	{
		return $this->action_id;
	}

	public function setAction_id($value)
	{
		$this->action_id = $value;
	}

	public function getAction_key()
	{
		return $this->action_key;
	}

	public function setAction_key($value)
	{
		$this->action_key = $value;
	}

	public function getInfinitive_verb()
	{
		return $this->infinitive_verb;
	}

	public function setInfinitive_verb($value)
	{
		$this->infinitive_verb = $value;
	}

	public function getPast_verb()
	{
		return $this->past_verb;
	}

	public function setPast_verb($value)
	{
		$this->past_verb = $value;
	}
}
?>
