<?php
/**
 * Model for app_installers
 * 
 * Generated by BlackPHP
 */

class app_installers_model extends Model
{
	/** @var int $installer_id ID de la tabla */
	private $installer_id;

	/** @var string $installer_nickname Usuario */
	private $installer_nickname;

	/** @var string $installer_password Resumen de contraseña */
	private $installer_password;

	/** @var string $installer_name Nombre del instalador */
	private $installer_name;

	/** @var string $installer_phone Teléfono */
	private $installer_phone;

	/** @var string $installer_email Correo electrónico */
	private $installer_email;

	/** @var string $creation_time Hora y fecha de creación */
	private $creation_time;

	/** @var int $status Eliminado, inactivo, activo */
	private $status;

	/**
	 * Constructor de la clase
	 * 
	 * Inicializa las propiedades table_name y primary_key
	 */
	public function __construct()
	{
		$this->table_name = "app_installers";
		$this->primary_key = "installer_id";
	}

	public function getInstaller_id()
	{
		return $this->installer_id;
	}

	public function setInstaller_id($value)
	{
		$this->installer_id = $value;
	}

	public function getInstaller_nickname()
	{
		return $this->installer_nickname;
	}

	public function setInstaller_nickname($value)
	{
		$this->installer_nickname = $value;
	}

	public function getInstaller_password()
	{
		return $this->installer_password;
	}

	public function setInstaller_password($value)
	{
		$this->installer_password = $value;
	}

	public function getInstaller_name()
	{
		return $this->installer_name;
	}

	public function setInstaller_name($value)
	{
		$this->installer_name = $value;
	}

	public function getInstaller_phone()
	{
		return $this->installer_phone;
	}

	public function setInstaller_phone($value)
	{
		$this->installer_phone = $value;
	}

	public function getInstaller_email()
	{
		return $this->installer_email;
	}

	public function setInstaller_email($value)
	{
		$this->installer_email = $value;
	}

	public function getCreation_time()
	{
		return $this->creation_time;
	}

	public function setCreation_time($value)
	{
		$this->creation_time = $value;
	}

	public function getStatus()
	{
		return $this->status;
	}

	public function setStatus($value)
	{
		$this->status = $value;
	}
}
?>
