<?php
/**
 * Model for app_methods
 * 
 * Generated by BlackPHP
 */

class app_methods_model extends Model
{
	/** @var int $method_id ID de la tabla */
	private $method_id;

	/** @var int $module_id ID del módulo */
	private $module_id;

	/** @var string $method_name Nombre del método */
	private $method_name;

	/** @var string $method_url URL del método (Nombre de la función PHP) */
	private $method_url;

	/** @var string $method_icon Ícono del método en el menú */
	private $method_icon;

	/** @var string $method_description Descripción del método */
	private $method_description;

	/** @var int $default_order Orden por defecto */
	private $default_order;

	/** @var int $status Estado 0:inactivo, 1:activo */
	private $status;

	/**
	 * Constructor de la clase
	 * 
	 * Inicializa las propiedades table_name y primary_key
	 */
	public function __construct()
	{
		$this->table_name = "app_methods";
		$this->primary_key = "method_id";
	}

	public function getMethod_id()
	{
		return $this->method_id;
	}

	public function setMethod_id($value)
	{
		$this->method_id = $value;
	}

	public function getModule_id()
	{
		return $this->module_id;
	}

	public function setModule_id($value)
	{
		$this->module_id = $value;
	}

	public function getMethod_name()
	{
		return $this->method_name;
	}

	public function setMethod_name($value)
	{
		$this->method_name = $value;
	}

	public function getMethod_url()
	{
		return $this->method_url;
	}

	public function setMethod_url($value)
	{
		$this->method_url = $value;
	}

	public function getMethod_icon()
	{
		return $this->method_icon;
	}

	public function setMethod_icon($value)
	{
		$this->method_icon = $value;
	}

	public function getMethod_description()
	{
		return $this->method_description;
	}

	public function setMethod_description($value)
	{
		$this->method_description = $value;
	}

	public function getDefault_order()
	{
		return $this->default_order;
	}

	public function setDefault_order($value)
	{
		$this->default_order = $value;
	}

	public function getStatus()
	{
		return $this->status;
	}

	public function setStatus($value)
	{
		$this->status = $value;
	}
}
?>
