<?php
/**
 * Model for app_elements
 * 
 * Generated by BlackPHP
 */

class app_elements_model extends Model
{
	/** @var int $element_id ID de la tabla */
	private $element_id;

	/** @var string $element_key Clave del elemento */
	private $element_key;

	/** @var string $element_name Nombre del elemento */
	private $element_name;

	/** @var string $element_gender M: Masculino, F: Femenino */
	private $element_gender;

	/** @var string $element_number S: Singular, P: Plural */
	private $element_number;

	/** @var int $unique_element Es un elemento único */
	private $unique_element;

	/** @var int $module_id ID del módulo */
	private $module_id;

	/** @var string $method_name Nombre del método para ver detalle */
	private $method_name;

	/**
	 * Constructor de la clase
	 * 
	 * Inicializa las propiedades table_name y primary_key
	 */
	public function __construct()
	{
		$this->table_name = "app_elements";
		$this->primary_key = "element_id";
	}

	public function getElement_id()
	{
		return $this->element_id;
	}

	public function setElement_id($value)
	{
		$this->element_id = $value;
	}

	public function getElement_key()
	{
		return $this->element_key;
	}

	public function setElement_key($value)
	{
		$this->element_key = $value;
	}

	public function getElement_name()
	{
		return $this->element_name;
	}

	public function setElement_name($value)
	{
		$this->element_name = $value;
	}

	public function getElement_gender()
	{
		return $this->element_gender;
	}

	public function setElement_gender($value)
	{
		$this->element_gender = $value;
	}

	public function getElement_number()
	{
		return $this->element_number;
	}

	public function setElement_number($value)
	{
		$this->element_number = $value;
	}

	public function getUnique_element()
	{
		return $this->unique_element;
	}

	public function setUnique_element($value)
	{
		$this->unique_element = $value;
	}

	public function getModule_id()
	{
		return $this->module_id;
	}

	public function setModule_id($value)
	{
		$this->module_id = $value;
	}

	public function getMethod_name()
	{
		return $this->method_name;
	}

	public function setMethod_name($value)
	{
		$this->method_name = $value;
	}
}
?>
