<?php
/**
 * Model for app_themes
 * 
 * Generated by BlackPHP
 */

class app_themes_model
{
	use ORM;

	/** @var int $theme_id ID de la tabla */
	private $theme_id;

	/** @var string $theme_name Nombre del tema */
	private $theme_name;

	/** @var string $theme_url Nombre de la carpeta pública */
	private $theme_url;


	/** @var string $_table_name Nombre de la tabla */
	private static $_table_name = "app_themes";

	/** @var string $_table_type Tipo de tabla */
	private static $_table_type = "BASE TABLE";

	/** @var string $_primary_key Llave primaria */
	private static $_primary_key = "theme_id";

	/** @var bool $_timestamps La tabla usa marcas de tiempo para la inserción y edición de datos */
	private static $_timestamps = false;

	/** @var bool $_soft_delete La tabla soporta borrado suave */
	private static $_soft_delete = false;

	/**
	 * Constructor de la clase
	 * 
	 * Se inicializan las propiedades de la clase.
	 * @param bool $default Determina si se utilizan, o no, los valores por defecto
	 * definidos en la base de datos.
	 **/
	public function __construct($default = true)
	{
		if($default)
		{
		}
	}

	public function getTheme_id()
	{
		return $this->theme_id;
	}

	public function setTheme_id($value)
	{
		$this->theme_id = $value === null ? null : (int)$value;
	}

	public function getTheme_name()
	{
		return $this->theme_name;
	}

	public function setTheme_name($value)
	{
		$this->theme_name = $value === null ? null : (string)$value;
	}

	public function getTheme_url()
	{
		return $this->theme_url;
	}

	public function setTheme_url($value)
	{
		$this->theme_url = $value === null ? null : (string)$value;
	}

	public function users()
	{
		users_model::flush();
		return users_model::where("theme_id", $this->theme_id);
	}
}
?>
