<?php
/**
 * Model for app_installers
 * 
 * Generated by BlackPHP
 */

class app_installers_model
{
	use ORM;

	/** @var string $_table_name Nombre de la tabla */
	private $_table_name;

	/** @var string $_primary_key Llave primaria */
	private $_primary_key;

	/** @var bool $_timestamps La tabla usa marcas de tiempo para la inserción y edición de datos */
	private $_timestamps;

	/** @var bool $_soft_delete La tabla soporta borrado suave */
	private $_soft_delete;

	/** @var int $installer_id ID de la tabla */
	private $installer_id;

	/** @var string $installer_nickname Usuario */
	private $installer_nickname;

	/** @var string $installer_password Resumen de contraseña */
	private $installer_password;

	/** @var string $installer_name Nombre del instalador */
	private $installer_name;

	/** @var string $installer_phone Teléfono */
	private $installer_phone;

	/** @var string $installer_email Correo electrónico */
	private $installer_email;

	/** @var string $creation_time Hora y fecha de creación */
	private $creation_time;

	/** @var int $status Eliminado, inactivo, activo */
	private $status;

	/**
	 * Constructor de la clase
	 * 
	 * Inicializa las propiedades generales de la tabla
	 */
	public function __construct()
	{
		$this->_table_name = "app_installers";
		$this->_primary_key = "installer_id";
		$this->_timestamps = false;
		$this->_soft_delete = true;
	}

	public function getInstaller_id()
	{
		return $this->installer_id;
	}

	public function setInstaller_id($value)
	{
		$this->installer_id = (int)$value;
	}

	public function getInstaller_nickname()
	{
		return $this->installer_nickname;
	}

	public function setInstaller_nickname($value)
	{
		$this->installer_nickname = (string)$value;
	}

	public function getInstaller_password()
	{
		return $this->installer_password;
	}

	public function setInstaller_password($value)
	{
		$this->installer_password = (string)$value;
	}

	public function getInstaller_name()
	{
		return $this->installer_name;
	}

	public function setInstaller_name($value)
	{
		$this->installer_name = (string)$value;
	}

	public function getInstaller_phone()
	{
		return $this->installer_phone;
	}

	public function setInstaller_phone($value)
	{
		$this->installer_phone = (string)$value;
	}

	public function getInstaller_email()
	{
		return $this->installer_email;
	}

	public function setInstaller_email($value)
	{
		$this->installer_email = (string)$value;
	}

	public function getCreation_time()
	{
		return $this->creation_time;
	}

	public function setCreation_time($value)
	{
		$this->creation_time = (string)$value;
	}

	public function getStatus()
	{
		return $this->status;
	}

	public function setStatus($value)
	{
		$this->status = (int)$value;
	}

	public function entities()
	{
		entities::flush();
		return entities::where("creation_installer", $this->installer_id);
	}
}
?>
