<?php
/**
 * Model for app_actions
 * 
 * Generated by BlackPHP
 */

class app_actions_model
{
	use ORM;

	/** @var int $action_id ID del registro */
	private $action_id;

	/** @var string $action_key Clave de la acción */
	private $action_key;

	/** @var string $infinitive_verb Verbo en infinitivo */
	private $infinitive_verb;

	/** @var string $past_verb Verbo en pasado */
	private $past_verb;


	/** @var string $_table_name Nombre de la tabla */
	private static $_table_name = "app_actions";

	/** @var string $_table_type Tipo de tabla */
	private static $_table_type = "BASE TABLE";

	/** @var string $_primary_key Llave primaria */
	private static $_primary_key = "action_id";

	/** @var bool $_timestamps La tabla usa marcas de tiempo para la inserción y edición de datos */
	private static $_timestamps = false;

	/** @var bool $_soft_delete La tabla soporta borrado suave */
	private static $_soft_delete = false;

	/**
	 * Constructor de la clase
	 * 
	 * Se inicializan las propiedades de la clase.
	 * @param bool $default Determina si se utilizan, o no, los valores por defecto
	 * definidos en la base de datos.
	 **/
	public function __construct($default = true)
	{
		if($default)
		{
		}
	}

	public function getAction_id()
	{
		return $this->action_id;
	}

	public function setAction_id($value)
	{
		$this->action_id = $value === null ? null : (int)$value;
	}

	public function getAction_key()
	{
		return $this->action_key;
	}

	public function setAction_key($value)
	{
		$this->action_key = $value === null ? null : (string)$value;
	}

	public function getInfinitive_verb()
	{
		return $this->infinitive_verb;
	}

	public function setInfinitive_verb($value)
	{
		$this->infinitive_verb = $value === null ? null : (string)$value;
	}

	public function getPast_verb()
	{
		return $this->past_verb;
	}

	public function setPast_verb($value)
	{
		$this->past_verb = $value === null ? null : (string)$value;
	}

	public function user_logs()
	{
		user_logs_model::flush();
		return user_logs_model::where("action_id", $this->action_id);
	}
}
?>
