<?php
/**
 * Model for available_modules
 * 
 * Generated by BlackPHP
 */

class availableModulesModel
{
	use ORM;

	/** @var int $module_id ID de la tabla */
	private $module_id;

	/** @var string $module_name Nombre del módulo */
	private $module_name;

	/** @var string $module_url URL del módulo */
	private $module_url;

	/** @var string $module_icon Ícono del módulo en el menú */
	private $module_icon;

	/** @var string $module_key Tecla de acceso rápido */
	private $module_key;

	/** @var string $module_description Descripción del módulo */
	private $module_description;

	/** @var int $default_order Orden por defecto */
	private $default_order;

	/** @var int $status Estado 0:inactivo, 1:activo */
	private $status;

	/** @var int $entity_id ID de la empresa */
	private $entity_id;

	/** @var int $user_id ID de la tabla */
	private $user_id;

	/** @var int $module_order Ubicación del módulo en el menú */
	private $module_order;


	/** @var string $_table_name Nombre de la tabla */
	private static $_table_name = "available_modules";

	/** @var string $_table_type Tipo de tabla */
	private static $_table_type = "VIEW";

	/** @var string $_primary_key Llave primaria */
	private static $_primary_key = "";

	/** @var bool $_timestamps La tabla usa marcas de tiempo para la inserción y edición de datos */
	private static $_timestamps = false;

	/** @var bool $_soft_delete La tabla soporta borrado suave */
	private static $_soft_delete = true;

	/** @var int|null $_deleted_status Valor a asignar en caso de borrado suave. */
	private static $_deleted_status = null;

	/**
	 * Constructor de la clase
	 * 
	 * Se inicializan las propiedades de la clase.
	 * @param bool $default Determina si se utilizan, o no, los valores por defecto
	 * definidos en la base de datos.
	 **/
	public function __construct($default = true)
	{
		if($default)
		{
			$this->module_id = 0;
			$this->status = 1;
			$this->user_id = 0;
			$this->module_order = 1;
		}
	}

	public function getModuleId()
	{
		return $this->module_id;
	}

	public function setModuleId($value)
	{
		$this->module_id = $value === null ? null : (int)$value;
	}

	public function getModuleName()
	{
		return $this->module_name;
	}

	public function setModuleName($value)
	{
		self::validateStringSize($value, 32);
		$this->module_name = $value === null ? null : (string)$value;
	}

	public function getModuleUrl()
	{
		return $this->module_url;
	}

	public function setModuleUrl($value)
	{
		self::validateStringSize($value, 32);
		$this->module_url = $value === null ? null : (string)$value;
	}

	public function getModuleIcon()
	{
		return $this->module_icon;
	}

	public function setModuleIcon($value)
	{
		self::validateStringSize($value, 32);
		$this->module_icon = $value === null ? null : (string)$value;
	}

	public function getModuleKey()
	{
		return $this->module_key;
	}

	public function setModuleKey($value)
	{
		self::validateStringSize($value, 1);
		$this->module_key = $value === null ? null : (string)$value;
	}

	public function getModuleDescription()
	{
		return $this->module_description;
	}

	public function setModuleDescription($value)
	{
		self::validateStringSize($value, 255);
		$this->module_description = $value === null ? null : (string)$value;
	}

	public function getDefaultOrder()
	{
		return $this->default_order;
	}

	public function setDefaultOrder($value)
	{
		$this->default_order = $value === null ? null : (int)$value;
	}

	public function getStatus()
	{
		return $this->status;
	}

	public function setStatus($value)
	{
		$this->status = $value === null ? null : (int)$value;
	}

	public function getEntityId()
	{
		return $this->entity_id;
	}

	public function setEntityId($value)
	{
		$this->entity_id = $value === null ? null : (int)$value;
	}

	public function getUserId()
	{
		return $this->user_id;
	}

	public function setUserId($value)
	{
		$this->user_id = $value === null ? null : (int)$value;
	}

	public function getModuleOrder()
	{
		return $this->module_order;
	}

	public function setModuleOrder($value)
	{
		$this->module_order = $value === null ? null : (int)$value;
	}
}
?>
