<?php
/**
 * Model for available_modules
 * 
 * Generated by BlackPHP
 */

class available_modules_model
{
	use ORM;

	/** @var int $module_id ID de la tabla */
	private $module_id;

	/** @var string $module_name Nombre del módulo */
	private $module_name;

	/** @var string $module_url URL del módulo */
	private $module_url;

	/** @var string $module_key Tecla de acceso rápido */
	private $module_key;

	/** @var string $module_description Descripción del módulo */
	private $module_description;

	/** @var int $default_order Orden por defecto */
	private $default_order;

	/** @var int $status Estado 0:inactivo, 1:activo */
	private $status;

	/** @var int $access_type Tipo de acceso al módulo */
	private $access_type;

	/** @var int $entity_id ID de la empresa */
	private $entity_id;

	/** @var int $user_id ID de la tabla */
	private $user_id;

	/** @var int $module_order Ubicación del módulo en el menú */
	private $module_order;


	/** @var string $_table_name Nombre de la tabla */
	private static $_table_name = "available_modules";

	/** @var string $_table_type Tipo de tabla */
	private static $_table_type = "VIEW";

	/** @var string $_primary_key Llave primaria */
	private static $_primary_key = "";

	/** @var bool $_timestamps La tabla usa marcas de tiempo para la inserción y edición de datos */
	private static $_timestamps = false;

	/** @var bool $_soft_delete La tabla soporta borrado suave */
	private static $_soft_delete = true;

	/**
	 * Constructor de la clase
	 * 
	 * Se inicializan las propiedades de la clase.
	 * @param bool $default Determina si se utilizan, o no, los valores por defecto
	 * definidos en la base de datos.
	 **/
	public function __construct($default = true)
	{
		if($default)
		{
			$this->module_id = 0;
			$this->status = 1;
			$this->user_id = 0;
			$this->module_order = 1;
		}
	}

	public function getModule_id()
	{
		return $this->module_id;
	}

	public function setModule_id($value)
	{
		$this->module_id = $value === null ? null : (int)$value;
	}

	public function getModule_name()
	{
		return $this->module_name;
	}

	public function setModule_name($value)
	{
		$this->module_name = $value === null ? null : (string)$value;
	}

	public function getModule_url()
	{
		return $this->module_url;
	}

	public function setModule_url($value)
	{
		$this->module_url = $value === null ? null : (string)$value;
	}

	public function getModule_key()
	{
		return $this->module_key;
	}

	public function setModule_key($value)
	{
		$this->module_key = $value === null ? null : (string)$value;
	}

	public function getModule_description()
	{
		return $this->module_description;
	}

	public function setModule_description($value)
	{
		$this->module_description = $value === null ? null : (string)$value;
	}

	public function getDefault_order()
	{
		return $this->default_order;
	}

	public function setDefault_order($value)
	{
		$this->default_order = $value === null ? null : (int)$value;
	}

	public function getStatus()
	{
		return $this->status;
	}

	public function setStatus($value)
	{
		$this->status = $value === null ? null : (int)$value;
	}

	public function getAccess_type()
	{
		return $this->access_type;
	}

	public function setAccess_type($value)
	{
		$this->access_type = $value === null ? null : (int)$value;
	}

	public function getEntity_id()
	{
		return $this->entity_id;
	}

	public function setEntity_id($value)
	{
		$this->entity_id = $value === null ? null : (int)$value;
	}

	public function getUser_id()
	{
		return $this->user_id;
	}

	public function setUser_id($value)
	{
		$this->user_id = $value === null ? null : (int)$value;
	}

	public function getModule_order()
	{
		return $this->module_order;
	}

	public function setModule_order($value)
	{
		$this->module_order = $value === null ? null : (int)$value;
	}
}
?>
