<?php
/**
 * Model for entity_options
 * 
 * Generated by BlackPHP
 */

class entity_options_model
{
	use ORM;

	/** @var int $entity_id ID de la tabla */
	private $entity_id;


	/** @var string $_table_name Nombre de la tabla */
	private static $_table_name = "entity_options";

	/** @var string $_table_type Tipo de tabla */
	private static $_table_type = "VIEW";

	/** @var string $_primary_key Llave primaria */
	private static $_primary_key = "";

	/** @var bool $_timestamps La tabla usa marcas de tiempo para la inserción y edición de datos */
	private static $_timestamps = false;

	/** @var bool $_soft_delete La tabla soporta borrado suave */
	private static $_soft_delete = false;

	/**
	 * Constructor de la clase
	 * 
	 * Se inicializan las propiedades de la clase.
	 * @param bool $default Determina si se utilizan, o no, los valores por defecto
	 * definidos en la base de datos.
	 **/
	public function __construct($default = true)
	{
		if($default)
		{
			$this->entity_id = 0;
		}
	}

	public function getEntity_id()
	{
		return $this->entity_id;
	}

	public function setEntity_id($value)
	{
		$this->entity_id = $value === null ? null : (int)$value;
	}
}
?>
