<?php
/**
 * Model for entity_methods
 * 
 * Generated by BlackPHP
 */

class entity_methods_model
{
	use ORM;

	/** @var string $_table_name Nombre de la tabla */
	private $_table_name;

	/** @var string $_primary_key Llave primaria */
	private $_primary_key;

	/** @var bool $_timestamps La tabla usa marcas de tiempo para la inserción y edición de datos */
	private $_timestamps;

	/** @var bool $_soft_delete La tabla soporta borrado suave */
	private $_soft_delete;

	/** @var int $cmethod_id ID de la tabla */
	private $cmethod_id;

	/** @var int $entity_id ID de la empresa */
	private $entity_id;

	/** @var int $method_id ID del método */
	private $method_id;

	/** @var int $method_order Orden en el que aoparecerá el método en el menú */
	private $method_order;

	/** @var string $creation_time - */
	private $creation_time;

	/** @var string $edition_time - */
	private $edition_time;

	/** @var int $status - */
	private $status;

	/**
	 * Constructor de la clase
	 * 
	 * Inicializa las propiedades generales de la tabla
	 */
	public function __construct()
	{
		$this->_table_name = "entity_methods";
		$this->_primary_key = "cmethod_id";
		$this->_timestamps = false;
		$this->_soft_delete = true;
	}

	public function getCmethod_id()
	{
		return $this->cmethod_id;
	}

	public function setCmethod_id($value)
	{
		$this->cmethod_id = (int)$value;
	}

	public function getEntity_id()
	{
		return $this->entity_id;
	}

	public function setEntity_id($value)
	{
		$this->entity_id = (int)$value;
	}

	public function getMethod_id()
	{
		return $this->method_id;
	}

	public function setMethod_id($value)
	{
		$this->method_id = (int)$value;
	}

	public function getMethod_order()
	{
		return $this->method_order;
	}

	public function setMethod_order($value)
	{
		$this->method_order = (int)$value;
	}

	public function getCreation_time()
	{
		return $this->creation_time;
	}

	public function setCreation_time($value)
	{
		$this->creation_time = (string)$value;
	}

	public function getEdition_time()
	{
		return $this->edition_time;
	}

	public function setEdition_time($value)
	{
		$this->edition_time = (string)$value;
	}

	public function getStatus()
	{
		return $this->status;
	}

	public function setStatus($value)
	{
		$this->status = (int)$value;
	}
}
?>
