<?php
/**
 * Model for entity_modules
 * 
 * Generated by BlackPHP
 */

class entity_modules_model extends Model
{
	/** @var int $cmodule_id ID de la tabla */
	private $cmodule_id;

	/** @var int $entity_id ID de la empresa */
	private $entity_id;

	/** @var int $module_id ID del módulo */
	private $module_id;

	/** @var int $module_order Ubicación del módulo en el menú */
	private $module_order;

	/** @var string $creation_time - */
	private $creation_time;

	/** @var string $edition_time - */
	private $edition_time;

	/** @var int $status - */
	private $status;

	/**
	 * Constructor de la clase
	 * 
	 * Inicializa las propiedades table_name y primary_key
	 */
	public function __construct()
	{
		$this->table_name = "entity_modules";
		$this->primary_key = "cmodule_id";
	}

	public function getCmodule_id()
	{
		return $this->cmodule_id;
	}

	public function setCmodule_id($value)
	{
		$this->cmodule_id = $value;
	}

	public function getEntity_id()
	{
		return $this->entity_id;
	}

	public function setEntity_id($value)
	{
		$this->entity_id = $value;
	}

	public function getModule_id()
	{
		return $this->module_id;
	}

	public function setModule_id($value)
	{
		$this->module_id = $value;
	}

	public function getModule_order()
	{
		return $this->module_order;
	}

	public function setModule_order($value)
	{
		$this->module_order = $value;
	}

	public function getCreation_time()
	{
		return $this->creation_time;
	}

	public function setCreation_time($value)
	{
		$this->creation_time = $value;
	}

	public function getEdition_time()
	{
		return $this->edition_time;
	}

	public function setEdition_time($value)
	{
		$this->edition_time = $value;
	}

	public function getStatus()
	{
		return $this->status;
	}

	public function setStatus($value)
	{
		$this->status = $value;
	}
}
?>
