<?php
/**
 * Model for user_logs
 * 
 * Generated by BlackPHP
 */

class user_logs_model extends Model
{
	/** @var int $log_id ID de la tabla */
	private $log_id;

	/** @var int $user_id ID del usuario */
	private $user_id;

	/** @var int $element_id ID del tipo de elemento */
	private $element_id;

	/** @var int $action_id Acción realizada */
	private $action_id;

	/** @var string $date_time Hora y fecha */
	private $date_time;

	/** @var int $element_link Enlace al elemento en cuestión */
	private $element_link;

	/**
	 * Constructor de la clase
	 * 
	 * Inicializa las propiedades table_name y primary_key
	 */
	public function __construct()
	{
		$this->table_name = "user_logs";
		$this->primary_key = "log_id";
	}

	public function getLog_id()
	{
		return $this->log_id;
	}

	public function setLog_id($value)
	{
		$this->log_id = $value;
	}

	public function getUser_id()
	{
		return $this->user_id;
	}

	public function setUser_id($value)
	{
		$this->user_id = $value;
	}

	public function getElement_id()
	{
		return $this->element_id;
	}

	public function setElement_id($value)
	{
		$this->element_id = $value;
	}

	public function getAction_id()
	{
		return $this->action_id;
	}

	public function setAction_id($value)
	{
		$this->action_id = $value;
	}

	public function getDate_time()
	{
		return $this->date_time;
	}

	public function setDate_time($value)
	{
		$this->date_time = $value;
	}

	public function getElement_link()
	{
		return $this->element_link;
	}

	public function setElement_link($value)
	{
		$this->element_link = $value;
	}
}
?>
