<?php
/**
 * Model for user_modules
 * 
 * Generated by BlackPHP
 */

class user_modules_model extends Model
{
	/** @var int $umodule_id ID de la tabla */
	private $umodule_id;

	/** @var int $module_id ID del módulo */
	private $module_id;

	/** @var int $user_id ID del usuario */
	private $user_id;

	/** @var int $access_type Tipo de acceso al módulo */
	private $access_type;

	/** @var int $creation_user - */
	private $creation_user;

	/** @var string $creation_time - */
	private $creation_time;

	/** @var int $edition_user - */
	private $edition_user;

	/** @var string $edition_time - */
	private $edition_time;

	/** @var int $status - */
	private $status;

	/**
	 * Constructor de la clase
	 * 
	 * Inicializa las propiedades table_name y primary_key
	 */
	public function __construct()
	{
		$this->table_name = "user_modules";
		$this->primary_key = "umodule_id";
	}

	public function getUmodule_id()
	{
		return $this->umodule_id;
	}

	public function setUmodule_id($value)
	{
		$this->umodule_id = $value;
	}

	public function getModule_id()
	{
		return $this->module_id;
	}

	public function setModule_id($value)
	{
		$this->module_id = $value;
	}

	public function getUser_id()
	{
		return $this->user_id;
	}

	public function setUser_id($value)
	{
		$this->user_id = $value;
	}

	public function getAccess_type()
	{
		return $this->access_type;
	}

	public function setAccess_type($value)
	{
		$this->access_type = $value;
	}

	public function getCreation_user()
	{
		return $this->creation_user;
	}

	public function setCreation_user($value)
	{
		$this->creation_user = $value;
	}

	public function getCreation_time()
	{
		return $this->creation_time;
	}

	public function setCreation_time($value)
	{
		$this->creation_time = $value;
	}

	public function getEdition_user()
	{
		return $this->edition_user;
	}

	public function setEdition_user($value)
	{
		$this->edition_user = $value;
	}

	public function getEdition_time()
	{
		return $this->edition_time;
	}

	public function setEdition_time($value)
	{
		$this->edition_time = $value;
	}

	public function getStatus()
	{
		return $this->status;
	}

	public function setStatus($value)
	{
		$this->status = $value;
	}
}
?>
