<?php
/**
 * Model for user_logs
 * 
 * Generated by BlackPHP
 */

class user_logs_model
{
	use ORM;

	/** @var int $log_id ID de la tabla */
	private $log_id;

	/** @var int $user_id ID del usuario */
	private $user_id;

	/** @var int $element_id ID del tipo de elemento */
	private $element_id;

	/** @var int $action_id Acción realizada */
	private $action_id;

	/** @var string $date_time Hora y fecha */
	private $date_time;

	/** @var int $element_link Enlace al elemento en cuestión */
	private $element_link;


	/** @var string $_table_name Nombre de la tabla */
	private static $_table_name = "user_logs";

	/** @var string $_table_type Tipo de tabla */
	private static $_table_type = "BASE TABLE";

	/** @var string $_primary_key Llave primaria */
	private static $_primary_key = "log_id";

	/** @var bool $_timestamps La tabla usa marcas de tiempo para la inserción y edición de datos */
	private static $_timestamps = false;

	/** @var bool $_soft_delete La tabla soporta borrado suave */
	private static $_soft_delete = false;

	/**
	 * Constructor de la clase
	 * 
	 * Se inicializan las propiedades de la clase.
	 * @param bool $default Determina si se utilizan, o no, los valores por defecto
	 * definidos en la base de datos.
	 **/
	public function __construct($default = true)
	{
		if($default)
		{
		}
	}

	public function getLog_id()
	{
		return $this->log_id;
	}

	public function setLog_id($value)
	{
		$this->log_id = $value === null ? null : (int)$value;
	}

	public function getUser_id()
	{
		return $this->user_id;
	}

	public function setUser_id($value)
	{
		$this->user_id = $value === null ? null : (int)$value;
	}

	public function getElement_id()
	{
		return $this->element_id;
	}

	public function setElement_id($value)
	{
		$this->element_id = $value === null ? null : (int)$value;
	}

	public function getAction_id()
	{
		return $this->action_id;
	}

	public function setAction_id($value)
	{
		$this->action_id = $value === null ? null : (int)$value;
	}

	public function getDate_time()
	{
		return $this->date_time;
	}

	public function setDate_time($value)
	{
		$this->date_time = $value === null ? null : (string)$value;
	}

	public function getElement_link()
	{
		return $this->element_link;
	}

	public function setElement_link($value)
	{
		$this->element_link = $value === null ? null : (int)$value;
	}
}
?>
