<?php
/**
 * Model for user_logs
 * 
 * Generated by BlackPHP
 */

class user_logs_model
{
	use ORM;

	/** @var string $_table_name Nombre de la tabla */
	private $_table_name;

	/** @var string $_primary_key Llave primaria */
	private $_primary_key;

	/** @var bool $_timestamps La tabla usa marcas de tiempo para la inserción y edición de datos */
	private $_timestamps;

	/** @var bool $_soft_delete La tabla soporta borrado suave */
	private $_soft_delete;

	/** @var int $log_id ID de la tabla */
	private $log_id;

	/** @var int $user_id ID del usuario */
	private $user_id;

	/** @var int $element_id ID del tipo de elemento */
	private $element_id;

	/** @var int $action_id Acción realizada */
	private $action_id;

	/** @var string $date_time Hora y fecha */
	private $date_time;

	/** @var int $element_link Enlace al elemento en cuestión */
	private $element_link;

	/**
	 * Constructor de la clase
	 * 
	 * Inicializa las propiedades generales de la tabla
	 */
	public function __construct()
	{
		$this->_table_name = "user_logs";
		$this->_primary_key = "log_id";
		$this->_timestamps = false;
		$this->_soft_delete = false;
	}

	public function getLog_id()
	{
		return $this->log_id;
	}

	public function setLog_id($value)
	{
		$this->log_id = $value;
	}

	public function getUser_id()
	{
		return $this->user_id;
	}

	public function setUser_id($value)
	{
		$this->user_id = $value;
	}

	public function getElement_id()
	{
		return $this->element_id;
	}

	public function setElement_id($value)
	{
		$this->element_id = $value;
	}

	public function getAction_id()
	{
		return $this->action_id;
	}

	public function setAction_id($value)
	{
		$this->action_id = $value;
	}

	public function getDate_time()
	{
		return $this->date_time;
	}

	public function setDate_time($value)
	{
		$this->date_time = $value;
	}

	public function getElement_link()
	{
		return $this->element_link;
	}

	public function setElement_link($value)
	{
		$this->element_link = $value;
	}
}
?>
