<?php
/**
 * Model for users
 * 
 * Generated by BlackPHP
 */

class users_model
{
	use ORM;

	/** @var string $_table_name Nombre de la tabla */
	private $_table_name;

	/** @var string $_primary_key Llave primaria */
	private $_primary_key;

	/** @var bool $_timestamps La tabla usa marcas de tiempo para la inserción y edición de datos */
	private $_timestamps;

	/** @var bool $_soft_delete La tabla soporta borrado suave */
	private $_soft_delete;

	/** @var int $user_id ID de la tabla */
	private $user_id;

	/** @var int $entity_id ID de la empresa */
	private $entity_id;

	/** @var string $user_name Nombre completo del usuario */
	private $user_name;

	/** @var string $nickname Usuario para inicio de sesión */
	private $nickname;

	/** @var string $email Correo electrónico */
	private $email;

	/** @var string $password Contraseña */
	private $password;

	/** @var int $theme_id Tema de visualización del usuario */
	private $theme_id;

	/** @var string $locale Idioma del usuario */
	private $locale;

	/** @var int $creation_user - */
	private $creation_user;

	/** @var string $creation_time - */
	private $creation_time;

	/** @var int $edition_user - */
	private $edition_user;

	/** @var string $edition_time - */
	private $edition_time;

	/** @var int $status - */
	private $status;

	/**
	 * Constructor de la clase
	 * 
	 * Inicializa las propiedades generales de la tabla
	 */
	public function __construct()
	{
		$this->_table_name = "users";
		$this->_primary_key = "user_id";
		$this->_timestamps = true;
		$this->_soft_delete = true;
	}

	public function getUser_id()
	{
		return $this->user_id;
	}

	public function setUser_id($value)
	{
		$this->user_id = $value;
	}

	public function getEntity_id()
	{
		return $this->entity_id;
	}

	public function setEntity_id($value)
	{
		$this->entity_id = $value;
	}

	public function getUser_name()
	{
		return $this->user_name;
	}

	public function setUser_name($value)
	{
		$this->user_name = $value;
	}

	public function getNickname()
	{
		return $this->nickname;
	}

	public function setNickname($value)
	{
		$this->nickname = $value;
	}

	public function getEmail()
	{
		return $this->email;
	}

	public function setEmail($value)
	{
		$this->email = $value;
	}

	public function getPassword()
	{
		return $this->password;
	}

	public function setPassword($value)
	{
		$this->password = $value;
	}

	public function getTheme_id()
	{
		return $this->theme_id;
	}

	public function setTheme_id($value)
	{
		$this->theme_id = $value;
	}

	public function getLocale()
	{
		return $this->locale;
	}

	public function setLocale($value)
	{
		$this->locale = $value;
	}

	public function getCreation_user()
	{
		return $this->creation_user;
	}

	public function setCreation_user($value)
	{
		$this->creation_user = $value;
	}

	public function getCreation_time()
	{
		return $this->creation_time;
	}

	public function setCreation_time($value)
	{
		$this->creation_time = $value;
	}

	public function getEdition_user()
	{
		return $this->edition_user;
	}

	public function setEdition_user($value)
	{
		$this->edition_user = $value;
	}

	public function getEdition_time()
	{
		return $this->edition_time;
	}

	public function setEdition_time($value)
	{
		$this->edition_time = $value;
	}

	public function getStatus()
	{
		return $this->status;
	}

	public function setStatus($value)
	{
		$this->status = $value;
	}
}
?>
