<?php
/**
 * Model for user_methods
 * 
 * Generated by BlackPHP
 */

class user_methods_model extends Model
{
	/** @var int $umethod_id ID de la tabla */
	private $umethod_id;

	/** @var int $user_id ID del usuario */
	private $user_id;

	/** @var int $method_id ID del método */
	private $method_id;

	/** @var int $access_type Tipo de acceso */
	private $access_type;

	/** @var int $creation_user - */
	private $creation_user;

	/** @var string $creation_time - */
	private $creation_time;

	/** @var int $edition_user - */
	private $edition_user;

	/** @var string $edition_time - */
	private $edition_time;

	/** @var int $status - */
	private $status;

	/**
	 * Constructor de la clase
	 * 
	 * Inicializa las propiedades table_name y primary_key
	 */
	public function __construct()
	{
		$this->table_name = "user_methods";
		$this->primary_key = "umethod_id";
	}

	public function getUmethod_id()
	{
		return $this->umethod_id;
	}

	public function setUmethod_id($value)
	{
		$this->umethod_id = $value;
	}

	public function getUser_id()
	{
		return $this->user_id;
	}

	public function setUser_id($value)
	{
		$this->user_id = $value;
	}

	public function getMethod_id()
	{
		return $this->method_id;
	}

	public function setMethod_id($value)
	{
		$this->method_id = $value;
	}

	public function getAccess_type()
	{
		return $this->access_type;
	}

	public function setAccess_type($value)
	{
		$this->access_type = $value;
	}

	public function getCreation_user()
	{
		return $this->creation_user;
	}

	public function setCreation_user($value)
	{
		$this->creation_user = $value;
	}

	public function getCreation_time()
	{
		return $this->creation_time;
	}

	public function setCreation_time($value)
	{
		$this->creation_time = $value;
	}

	public function getEdition_user()
	{
		return $this->edition_user;
	}

	public function setEdition_user($value)
	{
		$this->edition_user = $value;
	}

	public function getEdition_time()
	{
		return $this->edition_time;
	}

	public function setEdition_time($value)
	{
		$this->edition_time = $value;
	}

	public function getStatus()
	{
		return $this->status;
	}

	public function setStatus($value)
	{
		$this->status = $value;
	}
}
?>
